# Generated by Django 4.2.29 on 2026-04-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threshold_price",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("ABOVE", "माथि (Above)"), ("BELOW", "तल (Below)")],
                        max_length=5,
                    ),
                ),
                ("via_sms", models.BooleanField(default=True)),
                ("via_email", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="crops.crop",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
