# Generated by Django 4.2.29 on 2026-04-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="farm_size_ropani",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="id_back_photo",
            field=models.ImageField(blank=True, null=True, upload_to="id_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="id_front_photo",
            field=models.ImageField(blank=True, null=True, upload_to="id_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="id_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="id_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="is_id_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="main_crops",
            field=models.ManyToManyField(
                blank=True, related_name="farmers", to="crops.crop"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="municipality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="ward_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
