# Generated by Django 4.2.29 on 2026-04-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_business_type_user_farm_size_ropani_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_otp",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
