# Generated by Django 4.2.29 on 2026-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_nepali", models.CharField(max_length=100)),
                ("name_english", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("VEGETABLE", "तरकारी"),
                            ("FRUIT", "फलफूल"),
                            ("OTHER", "अन्य"),
                        ],
                        default="VEGETABLE",
                        max_length=20,
                    ),
                ),
                ("emoji", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name_nepali"],
            },
        ),
    ]
