# Generated by Django 4.2.29 on 2026-04-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "avg_price",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=8),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("KALIMATI", "Kalimati Market"),
                            ("MANUAL", "Manual Entry"),
                        ],
                        default="KALIMATI",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="crops.crop",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("crop", "date")},
            },
        ),
    ]
